services:
  web:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./certs:/certs:ro
      - ./public_html:/public_html:ro
      - ./templates:/etc/nginx/templates:ro
    environment:
      NGINX_PORT: 80
      NGINX_SSL_PORT: 443
      NGINX_HOST: '*.*'
    ports:
      - 80:80/tcp
      - 443:443/tcp
    # command: [nginx-debug, '-g', 'daemon off;'] # Uncomment to run in debug mode
